# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

language: en
assistant_id: helpdesk

# components: https://rasa.com/docs/rasa/components/
# tuning: https://rasa.com/docs/rasa/tuning-your-model/
# comparing pipelines: https://rasa.com/docs/rasa/testing-your-assistant/#comparing-nlu-pipelines
pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DucklingEntityExtractor
    url: "http://duckling:8000"
    dimensions: ["email"]
  - name: RegexEntityExtractor
    user_lookup_tables: False
    user_regexes: True
    user_word_boundaries: True
  - name: SpacyEntityExtractor
    dimensions: ["PERSON"]
  - name: DIETClassifier
    epochs: 600
    batch_strategy: balanced
  - name: EntitySynonymMapper
  - name: ResponseSelector
    featurizers: [ "convert", "cvf-word" ]
    constrain_similarities: true
    epochs: 600
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1


policies:
   - name: MemoizationPolicy
     max_history: 5
   - name: RulePolicy
     core_fallback_threshold: 0.4
     core_fallback_action_name: "action_handle_fallback"
     enable_fallback_prediction: True
   - name: TEDPolicy
     max_history: 8
     epochs: 600
     constrain_similarities: true
