services:
  core-server:
    image: helpdesk-core:latest
    build: .
    container_name: helpdesk-core
    ports:
      - "5006:5006"
    volumes:
      - ./:/app
    environment:
      - RASA_TELEMETRY_ENABLED=false
    command: bash -c "rasa run --enable-api --cors \"*\" --debug --model models/helpdesk_model.tar.gz --port \"5006\""
    networks:
      - all

  action-server:
    image: helpdesk-core:latest
    build: .
    container_name: helpdesk-action
    volumes:
      - ./actions:/app/actions
    environment:
      - DEV_ENV=local
    command: bash -c "rasa run actions --port \"5056\" --debug"
    ports:
      - "5056:5056"
    networks:
      - all

  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
